### ISSUE TITLE
cannot import name 'Dotenv' from 'dotenv' (python3)

### ISSUE THREAD

**Issue by carloocchiena** [pedroburon/dotenv#20]
Running Python 3.8.8

Correctly installed the module

`python-dotenv==0.19.2`

Following the instruction stated on the README.MD <br>
`from dotenv import Dotenv`

I got this error message:

`Exception has occurred: ImportError
cannot import name 'Dotenv' from 'dotenv'`

Apparently there are some workarounds going on already, but I feel like at least the docs needs to be tested or updated.

**Comment by WeaverStever** [comment]
@carloocchiena 

Running Python 3.6.9, in a venv project, using the pip installation, here is how I got it working.

~~~~
import dotenv
dotenv.load_dotenv()

import os
token = os.environ.get("api-token")
print (token)
~~~~

Of course in the root of the project, the .env file contains...

~~~~
api-token = '123456'
~~~~

**Comment by RoelAdriaans** [comment]
You are comparing [python-dotenv](https://pypi.org/project/python-dotenv/) against [dotenv](https://pypi.org/project/dotenv/).

dotenv hasn't had a release of any activity since 2015
python-dotenv is actively maintained and supports python 3.10.

You have installed the module `python-dotenv` , but are using the code snippit from `dotenv`.
